In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

## Tablas de frecuencia

Las tablas de frecuencia son en formato tabular, nos permite ver la distribución de una variable categórica, así como las gráficas de barras

### Ejemplo

In [2]:
df = pd.read_csv('./prestamos.csv')
df

                    estado nivel
0        Totalmente pagada     B
1       Cancelada (impago)     C
2        Totalmente pagada     C
3        Totalmente pagada     C
4                   Actual     B
...                    ...   ...
450956              Actual     D
450957              Actual     D
450958              Actual     D
450959              Actual     D
450960   Totalmente pagada     A

[450961 rows x 2 columns]

Con describe si da un numero en count que no son iguales hay perdida de información, unique se le conoce como los niveles que hay, el que más aparece (top) y la cantidad con la que aparece esa información (freq)

In [4]:
df.describe()

        estado   nivel
count   450961  450961
unique       4       7
top     Actual       B
freq    321185  132370

- unique: número de niveles por cada variable
- top: la categoría que más se repite en cada variable
- freq: la frecuencia de la categoría más común en cada variable

Ahora, si tiene variables numéricas `describe()`toma en cuenta estas variables descartando categóricas

In [5]:
df['numerica']=np.random.randint(0,50, (450961))
df

                    estado nivel  numerica
0        Totalmente pagada     B        46
1       Cancelada (impago)     C        45
2        Totalmente pagada     C        18
3        Totalmente pagada     C        30
4                   Actual     B        30
...                    ...   ...       ...
450956              Actual     D        32
450957              Actual     D         0
450958              Actual     D        46
450959              Actual     D        39
450960   Totalmente pagada     A        30

[450961 rows x 3 columns]

In [6]:
df.describe()

            numerica
count  450961.000000
mean       24.484341
std        14.422129
min         0.000000
25%        12.000000
50%        24.000000
75%        37.000000
max        49.000000

Si no queremos esto hacemos lo siguiente

In [8]:
#Excluye las variables numericas
df.describe(exclude=[np.number])

        estado   nivel
count   450961  450961
unique       4       7
top     Actual       B
freq    321185  132370

In [10]:
#Solo las frecuencias del dato categorico que queremos obtener
df['nivel'].value_counts()

nivel
B    132370
C    120875
D     74277
A     72490
E     34804
F     12904
G      3241
Name: count, dtype: int64

In [11]:
#AHora lo hacemos de manera ascendente
df['nivel'].value_counts(ascending=True)

nivel
G      3241
F     12904
E     34804
A     72490
D     74277
C    120875
B    132370
Name: count, dtype: int64

### Ejemplo practico
- escala en proporciones (normalizado)
- en orden descendente

Da el porcentaje que tenemos

In [13]:
#Variables categoricas
df['estado'].value_counts(normalize=True)

estado
Actual                0.712223
Totalmente pagada     0.215797
Cancelada (impago)    0.050273
Tarde                 0.021707
Name: proportion, dtype: float64

- Casi el 71% de los créditos se encuentran activos actualmente (estado = Actual)
- Un poco más del 21% de los créditos ya ha sido pagado (estado = Totalmente pagada)
- Aproximadamente un 5% de los créditos no se pueden recuperar (estado = Cancelada (impago))
- El 2.1% restante están activos pero los deudores no los han pagado a tiempo (estado = Tarde)

Ahora con nivel

In [14]:
tabla_nivel = df['nivel'].value_counts(normalize = True)
tabla_nivel

nivel
B    0.293529
C    0.268039
D    0.164708
A    0.160746
E    0.077177
F    0.028614
G    0.007187
Name: proportion, dtype: float64

In [15]:
print(f'Porcentaje de créditos medio-altos (B,C,D): {tabla_nivel['B':'D'].sum()}')
print(f'Porcentaje de créditos medio-bajos (E,F,G): {tabla_nivel['E':'G'].sum()}')

Porcentaje de créditos medio-altos (B,C,D): 0.7262756646361881
Porcentaje de créditos medio-bajos (E,F,G): 0.11297872765050636

- Tenemos 7 diferentes niveles de crédito, siendo B los créditos con montos más altos y G con los montos más bajos
- Aproximadamente el 72% de los créditos otorgados son de niveles medio-alto (B,C,D)
- El 16% de los créditos otorgados son de niveles altos (A)
- Aproximadamente el 12% de los créditos restantes son de niveles medio-bajo (E,F,G)

In [16]:
tabla_estado = df['estado'].value_counts(normalize=True)
tabla_estado

estado
Actual                0.712223
Totalmente pagada     0.215797
Cancelada (impago)    0.050273
Tarde                 0.021707
Name: proportion, dtype: float64

In [18]:
print(f'Porcentaje de estados Actual y Totalmente pagada: {tabla_estado['Actual':'Totalmente pagada'].sum()}')
print(f'Porcentaje de estados Cancelada (impago) y Tarde: {tabla_estado['Cancelada (impago)':'Tarde'].sum()}')

Porcentaje de estados Actual y Totalmente pagada: 0.9280203831373444
Porcentaje de estados Cancelada (impago) y Tarde: 0.07197961686265553