In [2]:
import numpy as np
from scipy import stats
import pandas as pd
import warnings 
import statistics as sts
warnings.filterwarnings('ignore')

## Medidas de tendencia central

Es la manera de cuantificar el valor más comúnmente encontrado en nuestros datos.

- Datos numéricos:
    - La media (promedio)
    - La mediana
- Datos categoricos:
    - La moda

Notación
- $\bar x$ cuando nos referimos al promedio de la muestra
- $\mu$ cuando nos referimos al promedio de la población

Si tiene una **distribución normal** nuestros datos numéricos, se debería ocupar la media

### Media o promedio

Es simplemente la suma de todos los valores dividida entre el número total de valores de la muestra

In [3]:
datos =[2,5,10,8]
media = sum(datos)/len(datos)
print(f'Media = {media}')

Media = 6.25

La limitación de la media es que es sensible a valores extremos (outliers)

#### Ejemplo

In [4]:
datos =[2,5,10,8, 300]
media = sum(datos)/len(datos)
print(f'Media = {media}')

Media = 65.0

### Mediana

Si hay variables numericas y no tienen una distribución normal o cuentan con valores extremos, resulta más adecuado usar la mediana:
> La mediana es simplemente el valor medio de un conjunto de datos cuando estos están ordenados de menor a mayor

#### Ejemplo

In [5]:
datos = np.array([2,1,6,10,5])
print(f'Datos originales: {datos}')
print(f'Datos ordenados: {np.sort(datos)}')
print(f'Datos originales: {np.median(datos)}')

Datos originales: [ 2  1  6 10  5]
Datos ordenados: [ 1  2  5  6 10]
Datos originales: 5.0

In [6]:
datos = np.array([2,1,6,10,5,9])
print(f'Datos originales: {datos}')
print(f'Datos ordenados: {np.sort(datos)}')
print(f'Datos originales: {np.median(datos)}')

Datos originales: [ 2  1  6 10  5  9]
Datos ordenados: [ 1  2  5  6  9 10]
Datos originales: 5.5

In [21]:
datos = np.array([-20,2,1,6,10,5,9,100,120])
print(f'Datos originales: {datos}')
print(f'Datos ordenados: {np.sort(datos)}')
print(f'Datos originales: {np.median(datos)}')

Datos originales: [-20   2   1   6  10   5   9 100 120]
Datos ordenados: [-20   1   2   5   6   9  10 100 120]
Datos originales: 6.0

### Moda

Su uso es como mediada de tendencia central para los datos categóricos:
> La moda es simplemente el valor más frecuente en la variable categórica

#### Ejemplo:

In [7]:
datos = np.array(['Bueno','Malo','Bueno','Regular','Bueno','Malo','Malo'])
print(datos)

['Bueno' 'Malo' 'Bueno' 'Regular' 'Bueno' 'Malo' 'Malo']

In [8]:
moda = sts.mode(datos)

In [9]:
print("Moda: ", moda)
#Nota: cambiaron la forma de hacer esto en la nueva versión
#print("Frecuencia de la moda: ", moda.count)

Moda:  Bueno

#### Ejemplo

Dataset crimenes.csv
1. ¿Cuales son la media y la mediana de la tasa de asesinatos?
2. ¿Cuales son la media y la mediana del numero total de asesinatos?

In [10]:
#Nota: el punto indica la carpteta actual
df = pd.read_csv('./crimenes.csv')
df

             State  Population  Murder.Rate Abbreviation
0          Alabama     4779736          5.7           AL
1           Alaska      710231          5.6           AK
2          Arizona     6392017          4.7           AZ
3         Arkansas     2915918          5.6           AR
4       California    37253956          4.4           CA
5         Colorado     5029196          2.8           CO
6      Connecticut     3574097          2.4           CT
7         Delaware      897934          5.8           DE
8          Florida    18801310          5.8           FL
9          Georgia     9687653          5.7           GA
10          Hawaii     1360301          1.8           HI
11           Idaho     1567582          2.0           ID
12        Illinois    12830632          5.3           IL
13         Indiana     6483802          5.0           IN
14            Iowa     3046355          1.9           IA
15          Kansas     2853118          3.1           KS
16        Kentucky     4339367          3.6           KY
17       Louisiana     4533372         10.3           LA
18           Maine     1328361          1.6           ME
19        Maryland     5773552          6.1           MD
20   Massachusetts     6547629          2.0           MA
21        Michigan     9883640          5.4           MI
22       Minnesota     5303925          1.6           MN
23     Mississippi     2967297          8.6           MS
24        Missouri     5988927          6.6           MO
25         Montana      989415          3.6           MT
26        Nebraska     1826341          2.9           NE
27          Nevada     2700551          6.0           NV
28   New Hampshire     1316470          0.9           NH
29      New Jersey     8791894          3.9           NJ
30      New Mexico     2059179          4.8           NM
31        New York    19378102          3.1           NY
32  North Carolina     9535483          5.1           NC
33    North Dakota      672591          3.0           ND
34            Ohio    11536504          4.0           OH
35        Oklahoma     3751351          4.5           OK
36          Oregon     3831074          2.0           OR
37    Pennsylvania    12702379          4.8           PA
38    Rhode Island     1052567          2.4           RI
39  South Carolina     4625364          6.4           SC
40    South Dakota      814180          2.3           SD
41       Tennessee     6346105          5.7           TN
42           Texas    25145561          4.4           TX
43            Utah     2763885          2.3           UT
44         Vermont      625741          1.6           VT
45        Virginia     8001024          4.1           VA
46      Washington     6724540          2.5           WA
47   West Virginia     1852994          4.0           WV
48       Wisconsin     5686986          2.9           WI
49         Wyoming      563626          2.7           WY

In [11]:
#Si son iguales hay una distribución normal
print(f'Promedio tasa de asesinatos: {df['Murder.Rate'].mean()}')
print(f'Mediana de asesinatos: {df['Murder.Rate'].median()}')

Promedio tasa de asesinatos: 4.066
Mediana de asesinatos: 4.0

promedio=mediana, tiene una distribución simétrica(es decir lado y lado de la media/mediana tenemos más o menos la misma distribución de datos).

Para obtener el **número total** de asesinatos, primero hay que calcular el número total de asesinatos por cada ciudad:

*Numero total de asesinatos = Poblacion * Tasa de asesinatos / 100.000*

In [12]:
df['Num_asesinatos'] = (1/100000)*df['Murder.Rate']*df['Population']
df

             State  Population  Murder.Rate Abbreviation  Num_asesinatos
0          Alabama     4779736          5.7           AL      272.444952
1           Alaska      710231          5.6           AK       39.772936
2          Arizona     6392017          4.7           AZ      300.424799
3         Arkansas     2915918          5.6           AR      163.291408
4       California    37253956          4.4           CA     1639.174064
5         Colorado     5029196          2.8           CO      140.817488
6      Connecticut     3574097          2.4           CT       85.778328
7         Delaware      897934          5.8           DE       52.080172
8          Florida    18801310          5.8           FL     1090.475980
9          Georgia     9687653          5.7           GA      552.196221
10          Hawaii     1360301          1.8           HI       24.485418
11           Idaho     1567582          2.0           ID       31.351640
12        Illinois    12830632          5.3           IL      680.023496
13         Indiana     6483802          5.0           IN      324.190100
14            Iowa     3046355          1.9           IA       57.880745
15          Kansas     2853118          3.1           KS       88.446658
16        Kentucky     4339367          3.6           KY      156.217212
17       Louisiana     4533372         10.3           LA      466.937316
18           Maine     1328361          1.6           ME       21.253776
19        Maryland     5773552          6.1           MD      352.186672
20   Massachusetts     6547629          2.0           MA      130.952580
21        Michigan     9883640          5.4           MI      533.716560
22       Minnesota     5303925          1.6           MN       84.862800
23     Mississippi     2967297          8.6           MS      255.187542
24        Missouri     5988927          6.6           MO      395.269182
25         Montana      989415          3.6           MT       35.618940
26        Nebraska     1826341          2.9           NE       52.963889
27          Nevada     2700551          6.0           NV      162.033060
28   New Hampshire     1316470          0.9           NH       11.848230
29      New Jersey     8791894          3.9           NJ      342.883866
30      New Mexico     2059179          4.8           NM       98.840592
31        New York    19378102          3.1           NY      600.721162
32  North Carolina     9535483          5.1           NC      486.309633
33    North Dakota      672591          3.0           ND       20.177730
34            Ohio    11536504          4.0           OH      461.460160
35        Oklahoma     3751351          4.5           OK      168.810795
36          Oregon     3831074          2.0           OR       76.621480
37    Pennsylvania    12702379          4.8           PA      609.714192
38    Rhode Island     1052567          2.4           RI       25.261608
39  South Carolina     4625364          6.4           SC      296.023296
40    South Dakota      814180          2.3           SD       18.726140
41       Tennessee     6346105          5.7           TN      361.727985
42           Texas    25145561          4.4           TX     1106.404684
43            Utah     2763885          2.3           UT       63.569355
44         Vermont      625741          1.6           VT       10.011856
45        Virginia     8001024          4.1           VA      328.041984
46      Washington     6724540          2.5           WA      168.113500
47   West Virginia     1852994          4.0           WV       74.119760
48       Wisconsin     5686986          2.9           WI      164.922594
49         Wyoming      563626          2.7           WY       15.217902

In [13]:
#Si son iguales hay una distribución normal
print(f'Promedio tasa de asesinatos: {df['Num_asesinatos'].mean()}')
print(f'Mediana de asesinatos: {df['Num_asesinatos'].median()}')

Promedio tasa de asesinatos: 273.99124876
Mediana de asesinatos: 162.662234

La media es diferente a la mediana (273 vs 162 asesinatos). Esto se debe a que las poblaciones se encuentran dentro de un rango amplio de valores, lo que al momento del cálculo afecta el número total de asesinatos, esto se debe a que tenemos **valores extremos (outliers)**

In [22]:
df['Num_asesinatos'].describe().to_frame()

       Num_asesinatos
count       50.000000
mean       273.991249
std        323.216195
min         10.011856
25%         54.193103
50%        162.662234
75%        359.342657
max       1639.174064

Por lo que podemos decir que en este caso del número de asesinatos, la medida más fiable es mediana (162 asesinatos)

|            | **Variable numérica** | **Variable categórica** | **¿Cuándo usar?**                                  | **Limitaciones** |
|:-----------|:---------------------:|:-----------------------:|:---------------------------------------------------|:-----------------|
| Media      |    &#10004;           |                         |Distribución normal y no hay presencia de *outliers*|Sensible a los outliers|
| Mediana    |    &#10004;           |                         |Distribución no normal y cuando hay valores extremos|
| Moda       |                       |         &#10004;        |                                                    |                  |